### ISSUE TITLE
Unhandled exception when a referenced dll does not exist

### ISSUE THREAD

**Issue by pethopal** [macaba/Markdig.Extensions.ScriptCs#2]
When I give a non-existing dll with #r, e.g.:
#r Not.Existing.dll

var result = scriptExecutor.ExecuteScript(fullScript);
in Markdig.Extensions.ScriptCs\ScriptCsRenderer.cs throws an exception, which is not handled...

This halts my application.

It works for me (and give the name of the missing dll):

```Csharp
global::ScriptCs.Contracts.ScriptResult result = null;
try
{
	result = scriptExecutor.ExecuteScript(fullScript);
	if (result.CompileExceptionInfo != null)
   ....
	MarkdownDocument.Instance.Reset();
}
catch (Exception exception)
{
	Exception ex = exception;
	if (exception is System.IO.FileNotFoundException notFoundEx)
	{
		ex = new Exception($"{notFoundEx.Message}: {notFoundEx.FileName}");
	}
	renderer.Write(Markdown.ToHtml(BuildMarkdownExceptionMessage(ex, options.ExceptionStackTrace), pipeline));
}
```

note: the script piece with the wrong dll will not run, but the others will run.

**Comment by macaba** [comment]
This looks like a really useful addition! Are you able to make a pull request?

**Comment by pethopal** [comment]
I'm working on the fork...
Pull request ready.

**Comment by macaba** [comment]
@pethopal - Thank you for your pull request, I have made the changes you suggested (or a similar form).
